[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = { version = "0.8.4", features = ["ws"] }
dotenvy = "0.15.7"
jsonwebtoken = "9.3.1"
meilisearch-sdk = "0.30.0"
mimalloc = "0.1.48"
serde = "1.0.226"
serde_json = "1.0.143"
sqlx = { version="0.8.6", features = ["postgres", "runtime-tokio", "macros", "time"] }
thiserror = "2.0.16"
time = { version = "0.3.44", features = ["serde"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
