import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import ClientProviders from "@/app/components/ClientProviders";
import FloatingMenu from "./components/FloatingMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jetbrainsMono.variable} antialiased bg-[#f0f4f8] dark:bg-[#0f172a] text-[#111111] dark:text-[#d4d4d4] transition-colors duration-[400] ease-in-out`}
      >
        <ClientProviders>
          <Header />
          <main className="flex w-full min-h-dvh items-center justify-center">
            {children}
            <FloatingMenu />
          </main>
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
